pipeline {
    agent any

    parameters {
        string(name: 'build_version', defaultValue: 'V1.0', description: 'Docker image tag')
    }

    environment {
        IMAGE_NAME = "Bala-Nakkala1/demo-java-app"
        SONAR_URL = "http://sonarqube:9000"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Bala-Nakkala/devops-demo-project.git'
            }
        }

        stage('Build') {
            steps {
                sh '''
                cd demo-java-app
                mvn clean package
                '''
            }
        }

        stage('Static Code Analysis') {
            steps {
                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh '''
                    cd demo-java-app
                    mvn sonar:sonar \
                      -Dsonar.login=$SONAR_AUTH_TOKEN \
                      -Dsonar.host.url=$SONAR_URL
                    '''
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                cd demo-java-app
                docker build -t $IMAGE_NAME:${build_version} .
                '''
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin
                    docker push $IMAGE_NAME:${build_version}
                    '''
                }
            }
        }

        stage('Update Deployment File') {
            environment {
                GIT_REPO_NAME = "devops-demo-project"
                GIT_USER_NAME = "Bala-Nakkala"
            }

            steps {
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                    git config user.email "balakrishna.nakkalangmail.com"
                    git config user.name "Balu Nakkala"

                    sed -i "s/tag: .*/tag: \\"${build_version}\\"/" helm/app/values.yaml

                    git add helm/app/values.yaml
                    git commit -m "Update deployment image to version ${build_version}" || true

                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                    '''
                }
            }
        }
    }
}
