services:
  jenkins:
    build:
      context: ./Jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8010:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-network
    environment:
      - JENKINS_OPTS=--httpPort=8080

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - ci-network

networks:
  ci-network:
    driver: bridge

volumes:
  jenkins_home:
